Repository googleapis/python-bigquery-sqlalchemy, pull requests merged in 2021-04, with the labels that each got.

#100 refactor: consolidate BigQuery client creation and set user-agent
  pybigquery/_helpers.py
  pybigquery/api.py
  pybigquery/sqlalchemy_bigquery.py
  setup.py
  testing/constraints-3.6.txt
  tests/unit/test_helpers.py
Labels: cla: yes

#106 fix: avoid 404 if dataset is deleted while listing tables or views
  pybigquery/sqlalchemy_bigquery.py
  tests/unit/test_sqlalchemy_bigquery.py
Labels: api: bigquery, cla: yes

#107 fix: correct classifiers in `setup.py`
  setup.py
Labels: api: bigquery, automerge, cla: yes

#117 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#114 test: use random suffix in DML test table
  tests/system/conftest.py
  tests/system/test_sqlalchemy_bigquery.py
Labels: api: bigquery, automerge, cla: yes

#120 fix: use `project_id` property from service account credentials
  pybigquery/_helpers.py
  tests/system/test_helpers.py
  tests/unit/test_helpers.py
Labels: api: bigquery, cla: yes

#119 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: bigquery, cla: yes, context: full, samples

#124 test: move table creation to temporary dataset
  tests/system/test_sqlalchemy_bigquery.py
Labels: api: bigquery, automerge, cla: yes

#125 chore: prevent normalization of semver versioning
  setup.py
Labels: api: bigquery, cla: yes

#129 fix: Select expressions no-longer force use of labels
  pybigquery/sqlalchemy_bigquery.py
  setup.py
  testing/constraints-3.6.txt
  tests/unit/conftest.py
  tests/unit/fauxdbi.py
  tests/unit/test_select.py
Labels: api: bigquery, cla: yes

#126 build: use PyPI API token in secret manager
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#132 chore(revert): revert preventing normalization
  setup.py
Labels: api: bigquery, automerge, cla: yes

#134 chore: add yoshi to CODEOWNERS
  .github/CODEOWNERS
Labels: api: bigquery, automerge, cla: yes
