Repository googleapis/python-bigquery-sqlalchemy, pull requests merged in 2021-08, with the labels that each got.

#198 feat: Rename pybigquery to sqlalchemy-bigquery
  .coveragerc
  .github/ISSUE_TEMPLATE/bug_report.md
  .repo-metadata.json
  AUTHORS
  CHANGELOG.md
  CONTRIBUTING.rst
  README.rst
  docs/conf.py
  docs/index.rst
  docs/multiprocessing.rst
  docs/pybigquery/api.rst
  noxfile.py
  owlbot.py
  pybigquery/api.py
  release-procedure.md
  setup.cfg
  setup.py
  sqlalchemy_bigquery/__init__.py
  sqlalchemy_bigquery/_helpers.py
  sqlalchemy_bigquery/base.py
  sqlalchemy_bigquery/parse_url.py
  sqlalchemy_bigquery/requirements.py
  sqlalchemy_bigquery/version.py
  tests/conftest.py
  tests/sqlalchemy_dialect_compliance/README.rst
  tests/sqlalchemy_dialect_compliance/conftest.py
  tests/sqlalchemy_dialect_compliance/test_dialect_compliance.py
  tests/system/__init__.py
  tests/system/conftest.py
  tests/system/test_alembic.py
  tests/system/test_helpers.py
  tests/system/test_sqlalchemy_bigquery.py
  tests/unit/conftest.py
  tests/unit/fauxdbi.py
  tests/unit/test_catalog_functions.py
  tests/unit/test_comments.py
  tests/unit/test_compiler.py
  tests/unit/test_compliance.py
  tests/unit/test_dialect_types.py
  tests/unit/test_engine.py
  tests/unit/test_helpers.py
  tests/unit/test_like_reescape.py
  tests/unit/test_parse_url.py
  tests/unit/test_select.py
  tests/unit/test_sqlalchemy_bigquery.py
  tests/unit/test_view.py
Labels: cla: yes, api: bigquery

#241 chore: Stop creating multiprocessing.rst
  owlbot.py
Labels: automerge, cla: yes, api: bigquery

#246 chore: add Yoshi and BigQuery teams to sample approvers
  .github/CODEOWNERS
Labels: automerge, cla: yes, samples, api: bigquery

#273 chore: consolidate several renovate-bot changes
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
Labels: automerge, cla: yes, api: bigquery

#279 chore: Update many dependencies
  samples/snippets/requirements.txt
Labels: cla: yes, api: bigquery

#282 chore: Update many dependencies: v2 for api-core, cloud-core and auth and bigquery
  noxfile.py
  owlbot.py
  samples/snippets/requirements.txt
  setup.py
Labels: cla: yes, api: bigquery

#287 feat: Announce pybigquery is obsolete. Use sqlalchemy-bigquery instead
  README.rst
  setup.py
Labels: cla: yes, api: bigquery

#278 fix: supports_multivalues_insert dialect option was mispelled
  sqlalchemy_bigquery/base.py
  tests/unit/test_sqlalchemy_bigquery.py
Labels: cla: yes, api: bigquery

#291 fix: dialect atribute wasn't provided
  sqlalchemy_bigquery/__init__.py
  sqlalchemy_bigquery/base.py
  tests/unit/test_sqlalchemy_bigquery.py
Labels: cla: yes, api: bigquery

#285 fix: in-operator literal binds not handled properly
  sqlalchemy_bigquery/base.py
  testing/constraints-3.6.txt
  tests/system/test_sqlalchemy_bigquery.py
  tests/unit/test_compliance.py
  tests/unit/test_select.py
Labels: cla: yes, api: bigquery

#275 fix: distinct doesn't work as a column wrapper
  sqlalchemy_bigquery/base.py
  tests/system/conftest.py
  tests/system/test_sqlalchemy_bigquery.py
Labels: cla: yes, api: bigquery

#319 chore: Update some dependencies
  dev_requirements.txt
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
Labels: cla: yes, api: bigquery
