Repository googleapis/python-bigquery-sqlalchemy, pull requests merged in 2021-03, with the labels that each got.

#87 chore: add CODEOWNERS file
  .github/CODEOWNERS
Labels: cla: yes

#95 chore: update pre-commit-config to latest template
  .pre-commit-config.yaml
  synth.metadata
Labels: cla: yes, context: none

#96 test: update system test fixtures to create necessary tables
  scripts/load_test_data.sh
  tests/system/conftest.py
  tests/system/data/sample.json
  tests/system/data/sample_one_row.json
  tests/system/data/schema.json
Labels: cla: yes

#97 docs: build documentation with Sphinx
  CONTRIBUTING.md
  README.rst
  docs/README.rst
  docs/changelog.md
  docs/index.rst
  docs/pybigquery/api.rst
Labels: automerge, cla: yes

#101 test: only create test tables if they do not already exist
  tests/system/conftest.py
Labels: cla: yes
