Repository googleapis/python-bigquery-sqlalchemy, pull requests merged in 2023-02, with the labels that each got.

#741 fix: Ensure repo install
  owlbot.py
  samples/snippets/noxfile.py
Labels: api: bigquery, size: s

#733 fix: remove type annotations from _struct.py
  sqlalchemy_bigquery/_struct.py
Labels: api: bigquery, size: xs

#737 docs: pass credentials as python dictionary
  README.rst
Labels: automerge, api: bigquery, size: s

#837 chore: updates owlbot to set pytest version and add troubleshooting output
  noxfile.py
  owlbot.py
Labels: api: bigquery, size: s
