Repository googleapis/python-bigquery-sqlalchemy, pull requests merged in 2025-03, with the labels that each got.

#1169 fix: resolve issue where pre-release versions of dependencies are installed
  setup.py
Labels: api: bigquery, size: s

#1168 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: api: bigquery, size: xl

#1167 feat: support job_config at query level
  sqlalchemy_bigquery/base.py
  tests/unit/test_sqlalchemy_bigquery.py
Labels: api: bigquery, size: s

#1175 fix: remove setup.cfg configuration for creating universal wheels
  setup.cfg
Labels: automerge, api: bigquery, size: xs
